- example:
    file: MultilevelMCMC_BasicInterface.cpp
    tag: MCMC
    title: Multilevel MCMC using a high level definition of model hiearchy.
    description: Uses a list of Gaussian models to define a multilevel sampling problem and applies Multilevel MCMC to it.
    doc_level: 1 # 1 for no description, 2 for minimal description, 3 for several descriptive cells, 4 for very good documentation

- example:
    file: MultilevelMCMC_AdvancedInterface.cpp
    tag: MCMC
    title: Multilevel MCMC using a low level definition of model hiearchy.
    description: Creates a SampleProblem that defines a hierarchy of simple Gaussian models and exposes the interface for more complicated multilevel formulations.  Sampling is then performed with Multilevel MCMC.
    doc_level: 1 # 1 for no description, 2 for minimal description, 3 for several descriptive cells, 4 for very good documentation


- example:
    file: ModelParallelMultilevelGaussianSampling.cpp
    tag: MCMC
    title: Multilevel MCMC with parallel model
    description: Defines a hierarchy of simple Gaussian models and applies Multilevel MCMC to it. The UQ method is sequential. However, the models themselves may exploit MPI parallelism. We use simple Gaussian target densities here, but the example can serve as a template for actually parallel models.
    doc_level: 1 # 1 for no description, 2 for minimal description, 3 for several descriptive cells, 4 for very good documentation


- example:
    file: FullParallelMultilevelGaussianSampling.cpp
    tag: MCMC
    title: Parallel Multilevel MCMC with parallel model
    description: Defines a hierarchy of simple Gaussian models and applies Multilevel MCMC to it. The MLMCMC method itself allows massive parallelization, and the forward model may be parallelized as well. We use simple Gaussian target densities here, but the example can serve as a template for actually parallel models.
    doc_level: 1 # 1 for no description, 2 for minimal description, 3 for several descriptive cells, 4 for very good documentation
