- example:
    file: MultilevelGaussianSampling.ipynb
    tag: MCMC
    title: Multilevel MCMC
    description: Defines a hierarchy of simple Gaussian models and applies Multilevel MCMC to it.
    doc_level: 2 # 1 for no description, 2 for minimal description, 3 for several descriptive cellss, 4 for very good documentation
