- example:
    file: DimensionIndependence.ipynb
    tag: MCMC
    title: Introduction to Dimension Independent MCMC Samplers
    description: This example demonstrates the use of dimension independent samplers like pCN for sampling problems that are naturally formulated on function spaces.
    doc_level: 3 # 1 for no description, 2 for minimal description, 3 for several descriptive cellss, 4 for very good documentation
