- example:
    file: CrankNicolson.ipynb
    tag: MCMC
    title: MCMC with pCN proposal
    description: Implement a simple MCMC method with preconditioned Crank-Nicolson proposal.
    doc_level: 1 # 1 for no description, 2 for minimal description, 3 for several descriptive cellss, 4 for very good documentation
